force-app/main/default/objects/EdvisorApplication__c/EdvisorApplication__c.object-meta.xml
<CustomObject>
    <label>Edvisor Application</label>
    <nameField>
        <displayFormat>EA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Edvisor Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EdvisorApplication__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Edvisor Applications</relationshipLabel>
    <relationshipName>Edvisor_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EdvisorApplication__c/fields/ProcessingStatus__c.field-meta.xml
<CustomField>
    <fullName>ProcessingStatus__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EdvisorApplication__c/fields/StudentEnrollmentId__c.field-meta.xml
<CustomField>
    <fullName>StudentEnrollmentId__c</fullName>
    <externalId>true</externalId>
    <label>Student Enrollment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EdvisorBatch.cls
global without sharing class EdvisorBatch implements Database.Batchable<String>, Database.AllowsCallouts, Database.Stateful {
    private final Datetime startDate;
    private final Datetime endDate;

    public EdvisorBatch(Datetime startDate, Datetime endDate) {
        this.startDate = startDate;
        this.endDate = endDate;
    }

    global Iterable<String> start(Database.BatchableContext bc) {
        return EdvisorService.getIds(startDate, endDate);
    }

    global void execute(Database.BatchableContext bc, List<String> scope) {
        try {
            Set<String> enrollmentIds = new Set<String>(scope);
            Set<String> enrollmentIdsToSend = new Set<String>();

            Map<String, EdvisorApplication__c> edvisorAppsMap = queryEdvisorApplications(enrollmentIds);
            List<EdvisorApplication__c> toInsert = new List<EdvisorApplication__c>();

            for (String enrollmentId : enrollmentIds) {
                if (!edvisorAppsMap.containsKey(enrollmentId)) {
                    EdvisorApplication__c newApp = new EdvisorApplication__c(StudentEnrollmentId__c = enrollmentId, ProcessingStatus__c = 'Received');
                    toInsert.add(newApp);
                    enrollmentIdsToSend.add(enrollmentId);
                }
            }
            if (!toInsert.isEmpty())
                insert toInsert;

            System.enqueueJob(new EdvisorEnrollmentQueueable(new List<String>(enrollmentIdsToSend)));
        } catch (Exception e) {
        }
    }

    // Método para buscar aplicações existentes
    private Map<String, EdvisorApplication__c> queryEdvisorApplications(Set<String> enrollmentIds) {
        Map<String, EdvisorApplication__c> edvisorApplications = new Map<String, EdvisorApplication__c>();

        for (EdvisorApplication__c edvisorApplication : [
            SELECT Id, StudentEnrollmentId__c, ProcessingStatus__c, Application__c
            FROM EdvisorApplication__c
            WHERE StudentEnrollmentId__c IN :enrollmentIds
        ]) {
            edvisorApplications.put(edvisorApplication.StudentEnrollmentId__c, edvisorApplication);
        }

        return edvisorApplications;
    }

    // Método finish
    global void finish(Database.BatchableContext bc) {
    }
}