force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Categorty__c/Course_Categorty__c.object-meta.xml
<CustomObject>
    <label>Course Category</label>
    <nameField>
        <label>Course Categorty  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Categorty__c/fields/Course_Type__c.field-meta.xml
<CustomField>
    <fullName>Course_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Type</label>
    <referenceTo>Course_Type__c</referenceTo>
    <relationshipLabel>Course Categories</relationshipLabel>
    <relationshipName>Course_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Type__c/Course_Type__c.object-meta.xml
<CustomObject>
    <label>Course Type</label>
    <nameField>
        <label>Course Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PdfTemplate__c/PdfTemplate__c.object-meta.xml
<CustomObject>
    <label>PDF Template</label>
    <nameField>
        <label>PDF Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PDF Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PDFEmailSenderTest.cls
@isTest
private class PDFEmailSenderTest {
    @isTest
    static void testSendEmail() {
        // Criar Account (Pessoa)
        Account acc = VirtualTestData.createAccount('Test', 'Teste', 'Brazil', Date.newInstance(2000, 5, 10), 'XPTO1234');
        insert acc;

        Course_Type__c courseType = VirtualTestData.createCourseType('Inglês Intensivo');
        insert courseType;

        Course_Categorty__c courseCategory = VirtualTestData.createCourseCategory('Language', courseType.Id);
        insert courseCategory;

        Course__c course = VirtualTestData.createCourse('Curso de Teste', courseCategory.Id);
        insert course;

        Account agent = VirtualTestData.createAgent('Agente Ativo', 'Active');
        insert agent;

        Product2 product = VirtualTestData.createProduct('Produto Teste', course.Id);
        insert product;

        Opportunity opp = VirtualTestData.createOpportunity(
            'Oportunidade Teste',
            'PO',
            Date.today().addDays(10),
            agent.Id,
            acc.Id,
            product.Id,
            courseCategory.Id,
            courseType.Id
        );
        insert opp;

        PDFTemplate__c template = VirtualTestData.createPdfTemplate(
            'Template de Teste',
            true,
            'PO',
            courseCategory.Id,
            'Bem-vindo {{Account.LastName}}! Data de nascimento: {{Account.PersonBirthdate}}. -----'
        );
        insert template;

        Quote invoice = VirtualTestData.createQuote('Teste Invoice', opp.Id);
        insert invoice;

        ContentVersion contentVersion = new ContentVersion(
            Title = 'a picture',
            PathOnClient = 'Pic.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;

        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        //create ContentDocumentLink  record
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.LinkedEntityId = invoice.Id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.ShareType = 'V';
        cdl.Visibility = 'AllUsers';
        insert cdl;

        Test.startTest();
        // Criar input e chamar método
        PDFEmailSender.EmailInput input = new PDFEmailSender.EmailInput();
        input.applicationId = opp.Id;
        input.templateType = 'PO';
        input.courseCategoryId = courseCategory.Id;
        input.invoiceId = invoice.Id;
        System.debug('invoiceid =' + invoice.Id);

        PDFEmailSender.sendEmail(new List<PDFEmailSender.EmailInput>{ input });
        Test.stopTest();
    }

    @isTest
    static void testExeptionSemInput() {
        Test.startTest();

        PDFEmailSender.sendEmail(new List<PDFEmailSender.EmailInput>{});
        Test.stopTest();
    }

    @isTest
    static void testExeptionComInputVazio() {
        Test.startTest();
        PDFEmailSender.EmailInput input = new PDFEmailSender.EmailInput();

        PDFEmailSender.sendEmail(new List<PDFEmailSender.EmailInput>{ input });
        Test.stopTest();
    }

    @isTest
    static void testExeptionSemInvoice() {
        // Criar Account (Pessoa)
        Account acc = VirtualTestData.createAccount('Test', 'Teste', 'Brazil', Date.newInstance(2000, 5, 10), 'XPTO1234');
        insert acc;

        Course_Type__c courseType = VirtualTestData.createCourseType('Inglês Intensivo');
        insert courseType;

        Course_Categorty__c courseCategory = VirtualTestData.createCourseCategory('Language', courseType.Id);
        insert courseCategory;

        Course__c course = VirtualTestData.createCourse('Curso de Teste', courseCategory.Id);
        insert course;

        Account agent = VirtualTestData.createAgent('Agente Ativo', 'Active');
        insert agent;

        Product2 product = VirtualTestData.createProduct('Produto Teste', course.Id);
        insert product;

        Opportunity opp = VirtualTestData.createOpportunity(
            'Oportunidade Teste',
            'PO',
            Date.today().addDays(10),
            agent.Id,
            acc.Id,
            product.Id,
            courseCategory.Id,
            courseType.Id
        );
        insert opp;

        PDFTemplate__c template = VirtualTestData.createPdfTemplate('Template de Teste', true, 'PO', courseCategory.Id, 'Bem-vindo. -----');
        insert template;

        Test.startTest();
        // Criar input e chamar método
        PDFEmailSender.EmailInput input = new PDFEmailSender.EmailInput();
        input.applicationId = opp.Id;
        input.templateType = 'PO';
        input.courseCategoryId = courseCategory.Id;

        PDFEmailSender.sendEmail(new List<PDFEmailSender.EmailInput>{ input });
        Test.stopTest();
    }

    @isTest
    static void testFetchOpportunityReturnsNull() {
        PDFEmailSender.EmailInput input = new PDFEmailSender.EmailInput();
        input.applicationId = '006000000000000'; // ID inválido
        input.templateType = 'PO';
        input.courseCategoryId = 'a1x000000000000';

        Test.startTest();
        PDFEmailSender.sendEmail(new List<PDFEmailSender.EmailInput>{ input });
        Test.stopTest();
    }

}