force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Course_Category__c.field-meta.xml
<CustomField>
    <fullName>Course_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Category</label>
    <referenceTo>Course_Categorty__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Categorty__c/Course_Categorty__c.object-meta.xml
<CustomObject>
    <label>Course Category</label>
    <nameField>
        <label>Course Categorty  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Categorty__c/fields/Course_Type__c.field-meta.xml
<CustomField>
    <fullName>Course_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Type</label>
    <referenceTo>Course_Type__c</referenceTo>
    <relationshipLabel>Course Categories</relationshipLabel>
    <relationshipName>Course_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Type__c/Course_Type__c.object-meta.xml
<CustomObject>
    <label>Course Type</label>
    <nameField>
        <label>Course Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <label>Payment Plan</label>
    <referenceTo>Payment_Plan__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plan__c/fields/Amount_paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_paid__c</fullName>
    <label>Amount paid</label>
    <summarizedField>Payment__c.Payment_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Payment__c.Payment_Status__c</field>
        <operation>equals</operation>
        <value>Paid</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment__c.Payment_Plan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/PdfTemplate__c/PdfTemplate__c.object-meta.xml
<CustomObject>
    <label>PDF Template</label>
    <nameField>
        <label>PDF Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PDF Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ReceiptControllerTest.cls
@isTest
public with sharing class ReceiptControllerTest {
    @isTest
    static void ReceiptControllerTest(){
        Account acc = VirtualTestData.createAccount('Test', 'Teste', 'Brazil', Date.newInstance(2000, 5, 10), 'XPTO1234');
        insert acc;

        Course_Type__c courseType = VirtualTestData.createCourseType('Inglês Intensivo');
        insert courseType;

        Course_Categorty__c courseCategory = VirtualTestData.createCourseCategory('Language', courseType.Id);
        insert courseCategory;

        Course__c course = VirtualTestData.createCourse('Curso de Teste', courseCategory.Id);
        insert course;

        Account agent = VirtualTestData.createAgent('Agente Ativo', 'Active');
        insert agent;

        Product2 product = new Product2(
            Name = 'Produto Teste',
            Parent_Course__c = course.Id,
            IsActive = true,
            Start_Date__c = Date.newInstance(2025, 12, 12),
            End_Date__c = Date.newInstance(2026, 12, 12)
        );
        insert product;

        Opportunity opp = new Opportunity(
            Name = 'Oportunidade Teste',
            StageName = 'PO',
            CloseDate = Date.today().addDays(10),
            AccountId = acc.Id,
            Agent__c = agent.Id,
            Course_Category__c = courseCategory.Id,
            Course_Type__c = courseType.Id,
            Product__c = product.Id,
            LeadCloseDate__c = Date.today().addDays(10)
        );
        insert opp;

        product.IsActive = true;
        update product;

        Id standardPBId = Test.getStandardPricebookId();

        PricebookEntry standardEntry = new PricebookEntry(
            Pricebook2Id = standardPBId,
            Product2Id = product.Id,
            UnitPrice = 100,
            IsActive = true
        );
        insert standardEntry;

        Pricebook2 customPB = new Pricebook2(
            Name = 'Custom Pricebook',
            IsActive = true
        );
        insert customPB;

        opp.Pricebook2Id = customPB.Id;
        update opp;

        PricebookEntry customEntry = new PricebookEntry(
            Pricebook2Id = customPB.Id,
            Product2Id = product.Id,
            UnitPrice = 100,
            IsActive = true
        );
        insert customEntry;

        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            Quantity = 1,
            UnitPrice = 100,
            PricebookEntryId = customEntry.Id,
            Description = 'Linha de teste',
            Start_Date__c = Date.newInstance(2024, 12, 12),
            End_Date__c = Date.newInstance(2025, 12, 12)
        );
        insert oli;

        Payment_Plan__c payPlan = new Payment_Plan__c(
            Name = 'Payment Plan Test'
        );
        insert payPlan;

        Payment__c pay = new Payment__c(
            Name = 'Payment Test',
            Opportunity__c = opp.Id,
            Payment_Plan__c = payPlan.Id,
            Payment_Amount__c = 100,
            Student_Name__c = acc.Id
        );
        insert pay;

        PDFTemplate__c template = VirtualTestData.createPdfTemplate('Receipt', true, '', courseCategory.Id, '----- Total Amount: € {{opportunity__r.Agent_Gross_Amout__c}}<br/>' +
            'Paid: {{opportunity__r.Amount_Paid__c}}<br/>' +
            'Outstanding: {{opportunity__r.Student_Outstanding_Balance__c}}' +
			'Payment amount: {{Payment_Amount__c}}' +
            '{table} -----');
        insert template;

        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', pay.Id);
        ReceiptController controller = new ReceiptController();
        Test.stopTest();

        System.assert(controller.decodedContent.contains('Total Amount'), 'Deve conter o texto formatado');
        System.assert(controller.decodedContent.contains('<hr'), 'HR deve ter sido inserido');
    }
}