force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Categorty__c/Course_Categorty__c.object-meta.xml
<CustomObject>
    <label>Course Category</label>
    <nameField>
        <label>Course Categorty  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Categorty__c/fields/Course_Type__c.field-meta.xml
<CustomField>
    <fullName>Course_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Type</label>
    <referenceTo>Course_Type__c</referenceTo>
    <relationshipLabel>Course Categories</relationshipLabel>
    <relationshipName>Course_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Type__c/Course_Type__c.object-meta.xml
<CustomObject>
    <label>Course Type</label>
    <nameField>
        <label>Course Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PdfTemplate__c/PdfTemplate__c.object-meta.xml
<CustomObject>
    <label>PDF Template</label>
    <nameField>
        <label>PDF Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PDF Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PdfContentControllerTest.cls
@isTest
public with sharing class PdfContentControllerTest {
    @isTest
    static void testPdfContentController_ACC() {
        Account acc = VirtualTestData.createAccount('Test', 'Teste', 'Brazil', Date.newInstance(2000, 5, 10), 'XPTO1234');
        insert acc;

        Course_Type__c courseType = VirtualTestData.createCourseType('Inglês Intensivo');
        insert courseType;

        Course_Categorty__c courseCategory = VirtualTestData.createCourseCategory('Language', courseType.Id);
        insert courseCategory;

        Course__c course = VirtualTestData.createCourse('Curso de Teste', courseCategory.Id);
        insert course;

        Account agent = VirtualTestData.createAgent('Agente Ativo', 'Active');
        insert agent;

        Product2 product = VirtualTestData.createProduct('Produto Teste', course.Id);
        insert product;

        Opportunity opp = VirtualTestData.createOpportunity('Oportunidade Teste', 'ACC', Date.today().addDays(10), agent.Id, acc.Id, product.Id, courseCategory.Id, courseType.Id);
        insert opp;

        PDFTemplate__c template = VirtualTestData.createPdfTemplate('Template de Teste', true, 'ACC', courseCategory.Id, 'Bem-vindo {{Account.LastName}}! Data de nascimento: {{Account.PersonBirthdate}}. -----');
        insert template;

        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', opp.Id);
        ApexPages.currentPage().getParameters().put('templateType', 'ACC');
        PdfContentController controller = new PdfContentController();
        Test.stopTest();

        System.assert(controller.decodedContent.contains('Bem-vindo'), 'Deve conter o texto formatado');
        System.assert(controller.decodedContent.contains('XPTO12345') == false, 'Não deve conter campos inexistentes');
        System.assert(controller.decodedContent.contains('<hr'), 'HR deve ter sido inserido');
        System.assertEquals(true, controller.exibirQrCode, 'Deveria exibir o QR code');
        System.assert(controller.qrCodeUrl.startsWith('https://api.qrserver.com'), 'QR Code URL deve ser gerada');
        System.assertNotEquals('', controller.Today, 'Today deve retornar a data formatada');
    }

    @isTest
    static void testPdfContentController_PO() {
        Account acc = VirtualTestData.createAccount('Test', 'Teste', 'Brazil', Date.newInstance(2000, 5, 10), 'XPTO1234');
        insert acc;

        Course_Type__c courseType = VirtualTestData.createCourseType('Inglês Intensivo');
        insert courseType;

        Course_Categorty__c courseCategory = VirtualTestData.createCourseCategory('Language', courseType.Id);
        insert courseCategory;

        Course__c course = VirtualTestData.createCourse('Curso de Teste', courseCategory.Id);
        insert course;

        Account agent = VirtualTestData.createAgent('Agente Ativo', 'Active');
        insert agent;

        Product2 product = VirtualTestData.createProduct('Produto Teste', course.Id);
        insert product;

        Opportunity opp = VirtualTestData.createOpportunity('Oportunidade Teste', 'PO', Date.today().addDays(10), agent.Id, acc.Id, product.Id, courseCategory.Id, courseType.Id);
        insert opp;

        PDFTemplate__c template = VirtualTestData.createPdfTemplate('Template de Teste', true, 'PO', courseCategory.Id, '');
        insert template;

        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', opp.Id);
        ApexPages.currentPage().getParameters().put('templateType', 'PO');
        PdfContentController controller = new PdfContentController();
        Test.stopTest();

        System.assertNotEquals('', controller.Today, 'Today deve retornar a data formatada');
    }
}